In [3]:

import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

##[solution 1] Matrix product is calculated manually

In [4]:

#The product of 2 matrices is calculated by multiplying the rows of the first one from left to right with each column of the second matrix from top to bottom.

#The calculation process of A x B is as follows

A = [[-1, 2, 3], [4, -5, 6], [7, 8, -9]] 
B = [[0, 2, 1], [0, 2, -8], [2, 9, -1]]

A0xB0: -10 + 20 +32 = 6
A0xB1:-12 + 22 +39 = 29
A0xB2:-11 + 2-8 +3-1 = -20
A1xB0: 40 - 50 +62 = 12
A1xB1: 42 - 52 +69 = 52
A1xB2: 41 - 5-8 +6-1 = 38
A2xB0: 70 + 80 -92 = -18
A2xB1: 72 + 82 -99 = -51
A2xB2: 71 + 8-8 -9*-1 = -48

AxB = [[6, 29, -20], [12, 52, 38], [-18, -52, -48]]

 Using Mockdown notation

$$A =\begin{bmatrix}-1, &amp; 2, &amp; 3\\4, &amp; -5, &amp; 6\\7, &amp; 8, &amp; -9\end{bmatrix}$$
,

$$B =\begin{bmatrix}0, &amp; 2, &amp; 1\\0, &amp; 2, &amp; -8\\2, &amp; 9, &amp; -1\end{bmatrix}$$
,

$$AB =\begin{bmatrix}0+0+6, &amp; -2+4+27, &amp;-1+(-16)+(-3)\\0+0+12, &amp; 8+(-10)+54, &amp; 4+40+(-6)\\0+0+(-18), &amp; 14+16+(-81), &amp; 7+(-64)+(-9)\end{bmatrix}$$
,

$$AB =\begin{bmatrix}6, &amp; 29, &amp; -20\\12, &amp; 52, &amp; 38\\-18, &amp; -51, &amp; -48\end {bmatrix}$$


##[solution 2] Calculation by NumPy function

In [5]:

import  numpy  as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
np.matmul(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])


##[Solution 3] Implementation of calculation of a certain element

In [7]:
print(f'The calculation of 0th row of matrix A and the 0th column of matrix B is:',a_ndarray[0,0] * b_ndarray[0,0] + a_ndarray[0,1] *b_ndarray[1,0] + a_ndarray[0,2] *b_ndarray[2,0])

The calculation of 0th row of matrix A and the 0th column of matrix B is: 6


#[solution 4]   function that performs matrix multiplication

In [8]:
def matrix_multiplication(matrix_A, matrix_B):
    matrix = np.zeros(9)
    product = matrix.reshape(3, 3)
   
    for x in range(len(matrix_A)):
        for y in range(len(matrix_B[0])):
            for z in range(len(matrix_B)):
                product[x][y] += matrix_A[x][z] * matrix_B[z][y]
    print(product)
matrix_multiplication(a_ndarray, b_ndarray)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]



##[solution 5] Judge the input whose calculation is not defined

In [9]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [10]:

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

if d_ndarray.shape[0] == e_ndarray.shape[1]:
    print(product_of_matrix(d_ndarray, e_ndarray))
else:
    print("Sorry! the following matrices are not aligned!")

Sorry! the following matrices are not aligned!


##[solution 6] Transposition

In [11]:
print('The product of the matrix when transposing matrix a is: ')
np.dot(a_ndarray.T,b_ndarray)

The product of the matrix when transposing matrix a is: 


array([[ 14,  69, -40],
       [ 16,  66,  34],
       [-18, -63, -36]])